applications:
  - id: "aura-app"
    name: "AURA Supervisor Application"
    privacyKeys: ["default-key"]

registry:
  aura-identifier-agent:
    options: []
    runtime:
      type: "executable"
      command: ["bash", "-c", "cd ../agents/identifier_agent && ../../venv/Scripts/python.exe -m uvicorn main:app --host 127.0.0.1 --port 8001"]
      environment:
        - name: "USERPROFILE"
          value: "%USERPROFILE%"

  # This agent definition is now clean and portable.
  aura-procedure-agent:
    options: []
    runtime:
      type: "executable"
      command: ["bash", "-c", "cd ../agents/procedure_agent && ../../venv/Scripts/python.exe -m uvicorn main:app --host 127.0.0.1 --port 8002"]
      environment:
        - name: "USERPROFILE"
          value: "%USERPROFILE%"

  aura-summarizer-agent:
    options: []
    runtime:
      type: "executable"
      command: ["bash", "-c", "cd ../agents/summarizer_agent && ../../venv/Scripts/python.exe -m uvicorn main:app --host 127.0.0.1 --port 8003"]
      environment:
        - name: "USERPROFILE"
          value: "%USERPROFILE%"

  # New agent registration
  aura-command-agent:
    options: []
    runtime:
      type: "executable"
      command: ["bash", "-c", "cd ../agents/command_agent && ../../venv/Scripts/python.exe -m uvicorn main:app --host 0.0.0.0 --port 8004"]
      environment:
        - name: "USERPROFILE"
          value: "%USERPROFILE%"
  
  aura-annotator-agent:
    options: []
    runtime:
      type: "executable"
      command: ["bash", "-c", "cd ../agents/annotator_agent && ../../venv/Scripts/python.exe -m uvicorn main:app --host 0.0.0.0 --port 8005"]
      environment:
        - name: "USERPROFILE"
          value: "%USERPROFILE%"

  # New Groq Llama Vision Agent registration
  aura-groq-llama-vision-agent:
    options: []
    runtime:
      type: "executable"
      command: ["bash", "-c", "cd ../agents/groq_llama_vision_agent && ../../venv/Scripts/python.exe -m uvicorn main:app --host 0.0.0.0 --port 8006"]
      environment:
        - name: "USERPROFILE"
          value: "%USERPROFILE%" 