version: '3.8'

services:
  # The Django Supervisor Service is now the only service managed by Docker.
  supervisor:
    build:
      context: ./aura  # Ensure this matches the case-sensitive name of your Django project folder
      dockerfile: ../Dockerfile.supervisor
    ports:
      # Expose port 8000 to the host machine so Nginx can proxy to it.
      - "8000:8000"
    # The command to run when the container starts. It applies migrations and starts Gunicorn.
    command: ["/app/startup.sh"]
    # Mount the 'database' directory to persist the SQLite file.
    volumes:
      - ./database:/app/database
      # Mount the 'media' directory to persist user-uploaded images.
      - ./media:/app/media
    environment:
      # Tell Django which settings file to use.
      - DJANGO_SETTINGS_MODULE=aura.settings # Ensure 'Aura' matches your Django config folder name
    # CRITICAL: This allows the container to communicate with agents
    # running on the host machine (which are launched by Coral).
    extra_hosts:
      - "host.docker.internal:host-gateway"