# Generated by Django 5.2.4 on 2025-07-06 14:59

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='final_summary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='identified_component',
        ),
        migrations.AddField(
            model_name='job',
            name='final_report_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED_SUCCESS', 'Completed Successfully'), ('COMPLETED_FAILURE', 'Completed with Failure')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='New AURA Session', max_length=255),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('USER', 'Human Technician'), ('AURA', 'Aura Assistant')], max_length=20)),
                ('user_text_input', models.TextField(blank=True, null=True)),
                ('user_image_input', models.ImageField(blank=True, null=True, upload_to=core.models.user_image_path)),
                ('aura_text_response', models.TextField(blank=True, null=True)),
                ('aura_annotated_image', models.ImageField(blank=True, null=True, upload_to=core.models.aura_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parsed_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.job')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='JobLog',
        ),
    ]
