# Generated by Django 5.2.4 on 2025-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_job_final_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=255, unique=True)),
                ('steps', models.JSONField(default=list)),
                ('safety_warnings', models.JSONField(default=list)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
